# Generated by Django 2.2.7 on 2019-11-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatUser',
        ),
    ]
